### ISSUE TITLE
PBMC Dataset used in paper to produce Figure 6

### ISSUE THREAD

**Issue by fbrundu** [Vivianstats/scImpute#10]
Dear Vivian,
I'd like to use the same dataset that you used in scImpute paper. However, I'm unable to infer which one it is from [10X webpage](https://support.10xgenomics.com/single-cell-gene-expression/datasets).
The interested dataset is the one used to produce Figure 6:

> The dataset contains 4,500 peripheral blood mononuclear cells (PBMCs) of nine immune cell types, with 500 cells of each type.

I am contacting you since the Fresh 68k PBMCs (Donor A) has 68k cells, the other ones have different size (not 4.5k cells), so I don't understand which one you used.

**Edit**
Is the dataset the following:
https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.3.0/pbmc4k
?

Thanks,
Francesco

**Comment by Vivianstats** [comment]
Hello Francesco,

If you go to their website (https://support.10xgenomics.com/single-cell-gene-expression/datasets), you can see a list of cell types (Monocytes, B cells, etc.). For example, Monocytes data is distributed here: https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/cd14_monocytes

I randomly draw 500 cells from each type so that I can have true cell labels. I did not use the larger datasets since the true cell labels are missing.

**Comment by fbrundu** [comment]
Hi Vivian,
Ok. How did you correct for batch effects?

**Comment by Vivianstats** [comment]
Hello Francesco,
I'm aware that there are normalization methods developed for scRNA-seq data, but in my analysis I just normalized the raw data by total counts.

**Comment by fbrundu** [comment]
Ok, thanks.

**Comment by sophial05** [comment]
Hi Vivian, I was just wondering if you could please share the dataset that you used to produce Figure 6? Thanks!

**Comment by Vivianstats** [comment]
Hi Sophia,

You can directly download the data from 10x genomics website:
https://support.10xgenomics.com/single-cell-gene-expression/datasets
under section: Single Cell 3' Paper: Zheng et al. 2017

Best,
Vivian

**Comment by sophial05** [comment]
Thank you so much!
