### ISSUE TITLE
Error in mclapply

### ISSUE THREAD

**Issue by Cady123** [Vivianstats/scImpute#6]
Hi!

I'm new to single-cell sequencing data and r programming. When I try to use scImpute to impute my data, I got following problem and not so sure how to carry on. I sincerely hope you could help me out. Thanks!

scImpute::scimpute(count_path = "dataNeed.csv", out_dir = "C:/360Downloads/R_workspace",Kcluster = 9)
[1] "reading in raw count matrix ..."
[1] "number of genes in raw count matrix 26178"
[1] "number of cells in raw count matrix 1529"
[1] "inferring cell similarities ..."
Error in mclapply(1:J, function(id1) { : 
  'mc.cores' > 1 is not supported on Windows

**Comment by Vivianstats** [comment]
Hello Cady123,

The behind this problem is that the Windows system does not support the mclapply function (used for parallel computation). You might consider setting ncores to 1 if your dataset is not too large. Otherwise, there seem to be some solutions to use the parallel package on Windows, for example:
https://github.com/nathanvan/parallelsugar
But I've never tried these solutions before so I'm not sure whether they can solve the problem.
