### ISSUE TITLE
Error during cell similarity inference

### ISSUE THREAD

**Issue by fbrundu** [Vivianstats/scImpute#8]
Dear Vivian,
I am running on some error while running scImpute:

    Error in rowSums(xi^2) : 'x' must be an array of at least two dimensions

I am running scImpute using this command:

    scimpute(
        'data.scimputein.txt',
        infile='txt',
        outfile='txt',
        out_dir='aa_',
        drop_thre=0.5,
        Kcluster=1,
        ncores=2)

The full trace of scImpute is:

    [1] "reading in raw count matrix ..."
    [1] "number of genes in raw count matrix 13054"
    [1] "number of cells in raw count matrix 3408"
    [1] "inferring cell similarities ..."
    Error in rowSums(xi^2) : 'x' must be an array of at least two dimensions

I send you the link to an example dataset: https://www.dropbox.com/s/51y1bd1z7a65qh5/data.7z?dl=0

Thanks,
Francesco

**Comment by Vivianstats** [comment]
Hello Francesco,

I update the package a couple of hours ago, so I'm not sure which version you are having problems with. v0.0.4 does not support the option Kcluster = 1, but v0.0.5 does.
I tested v0.0.5 with your example data and was able to obtain the imputation results. Please let me know if you are having difficulties with the newest version. (Please note that with ncores = 2, it takes some time for the computation to finish, since you have ~3000 cells.)

Best,
Vivian

**Comment by fbrundu** [comment]
Dear Vivian,
Thanks. Now it works with Kcluster = 1, however I noticed that if I use ncores = 4 it doesn't start "estimating dropout probability for type 1 ...". This is a second issue and I'm not sure if it can be reproduced every time, but maybe it could be interesting for you to investigate.

Thanks for the prompt reply,
Francesco
